In [1]:
# import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
# load data
dataset = pd.read_csv('data30062023/Data.csv')

In [13]:
dataset.head()

Negara  Umur       Gaji Transaksi
0   Jakarta  44.0  8000000.0     Tidak
1   Bandung  27.0  6500000.0        Ya
2  Surabaya  30.0  4500000.0     Tidak
3   Bandung  38.0  7500000.0     Tidak
4  Surabaya  40.0        NaN        Ya

In [23]:
dataset.Transaksi.unique()

array(['Tidak', 'Ya'], dtype=object)

In [25]:
dataset.Transaksi = dataset.Transaksi.map({'Tidak':0, 'Ya':1})

In [26]:
dataset.head()

Negara  Umur       Gaji  Transaksi
0   Jakarta  44.0  8000000.0          0
1   Bandung  27.0  6500000.0          1
2  Surabaya  30.0  4500000.0          0
3   Bandung  38.0  7500000.0          0
4  Surabaya  40.0        NaN          1

In [27]:
# feature scaling
from sklearn.preprocessing import MinMaxScaler
sc_X = MinMaxScaler()
scaled_X = sc_X.fit_trasform(X[:, 1:3])

AttributeError: 'MinMaxScaler' object has no attribute 'fit_trasform'

In [28]:
scaled_X

NameError: name 'scaled_X' is not defined

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [30]:
X_train

array([[4.40e+01, 8.00e+06],
       [4.80e+01, 9.75e+06],
       [3.00e+01, 4.50e+06],
       [3.70e+01, 6.70e+06],
       [4.00e+01,      nan],
       [3.80e+01, 7.50e+06],
       [     nan, 8.25e+06]])

In [31]:
X_test

array([[5.000e+01, 7.674e+06],
       [2.700e+01, 6.500e+06],
       [3.500e+01, 1.000e+07]])

In [32]:
X

array([[4.400e+01, 8.000e+06],
       [2.700e+01, 6.500e+06],
       [3.000e+01, 4.500e+06],
       [3.800e+01, 7.500e+06],
       [4.000e+01,       nan],
       [3.500e+01, 1.000e+07],
       [      nan, 8.250e+06],
       [4.800e+01, 9.750e+06],
       [5.000e+01, 7.674e+06],
       [3.700e+01, 6.700e+06]])